services:
  loki:
    image: grafana/loki:latest
    networks:
      - ocr-net
    ports:
      - 3100:3100
    volumes:
      - ./configs/loki-config.yml:/etc/loki/loki-config.yaml
      - ./loki-data:/tmp/loki
  promtail:
    image: grafana/promtail:latest
    networks:
      - ocr-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yaml
  grafana:
    image: grafana/grafana
    depends_on:
    - loki
    networks:
      - ocr-net
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.web.rule=Host(`eremos.cloud`) && PathPrefix(`/admin`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.middlewares.admin-ip.ipallowlist.sourcerange=192.168.1.14"

volumes:
  loki-data:
  configs:

networks:
  ocr-net:
    external: true
