services:
  loki:
    image: grafana/loki:latest
    networks:
      - ocr-net
    ports:
      - 3100:3100
    volumes:
      - ./configs/loki-config.yml:/etc/loki/local-config.yml
  promtail:
    image: grafana/promtail:latest
    networks:
      - ocr-net
    command: -config.file=/etc/promtail/docker-config.yml
    depends_on:
      - loki
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    image: grafana/grafana
    networks:
      - ocr-net
    ports:
      - 3200:3000
    volumes:
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    labels:
      - "traefik.http.routers.web.rule=Host(`eremos.cloud`) && PathPrefix(`/admin`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      #- "traefik.http.middlewares.admin-ip.ipallowlist.sourcerange=${PUBLIC_IP}"

volumes:
  grafana-data:
  configs:

networks:
  ocr-net:
    external: true
