services:
  keycloak_db:
      image: postgres:latest
      networks:
        - ocr-net
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak # Change soon
        - POSTGRES_PASSWORD=keycloak # Change soon
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d ocr_db -U admin" ]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - keycloak-db:/var/lib/postgresql/data
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - ocr-net
    ports:
      - 3300:8080
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin # Change soon 
      KEYCLOAK_ADMIN_PASSWORD: admin # Change soon 
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`localhost`) && PathPrefix(`/auth`)" # Change soon
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
    depends_on:
      - keycloak_db
  
  
volumes:
  keycloak-db:

networks:
  ocr-net:
    external: true
