server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [flog]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"

  - job_name: docker
    pipeline_stages:
      - docker: {} # Parses JSON log format
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    relabel_configs:
      # Extract container ID from log file path
      - source_labels: [__path__]
        regex: '.*/containers/(.*)/.*\.log'
        target_label: container_id

      # Extract container name dynamically
      - source_labels: [container_id]
        target_label: container_name
        action: replace

      # Extract the Docker labels (requires Promtail to be run with access to the Docker socket)
      - action: labelmap
        regex: __meta_docker_container_label_(.+)

      # Filter only containers that have the label `promtail.enabled=true`
      - source_labels: [__meta_docker_container_label_promtail_enabled]
        regex: "true"
        action: keep
